### PR TITLE
Added ability to use string data instead of filenames

### PR DESCRIPTION
**Pull request by ghost**
* Kept all public methods
* Added additional public methods with string parameters
* Converted all private methods to act on strings

### CODE REVIEW

**Comment by jckgore** [comment]
I probably should have revved up the minor before my PR.

**Comment by oocx** [comment]
Hi,

Thanks for contributing to this project!

I'm using semantic-release, which calculates a new version based on [commit message conventions](https://www.conventionalcommits.org/en/v1.0.0/). Can you please add "feat: " to your commit message? This will increase the minor version.

I'll add that info to the readme later. I did not expect that anybody else would work on this project :).

**Comment by oocx** [comment]
Oh and if you don't mind, please also add a unit test for your new method.

**Comment by jckgore** [comment]
I added a cheesy unit test that checks the file and string version give the same result. And I also threw in a commit with 'feat:' to rev the minor.

**Comment by oocx** [comment]
I just published the new package to NuGet.org. Thanks again for your contribution!

**Comment by ghost** [comment]
This was technically my first GitHub PR. Thanks for the original code and for maintaining!
________________________________

**Pull request merged**
